# Base image.
FROM node:22.7.0-alpine

# Set evironment variables. 
ENV LANG=C.UTF-8

# Arguments In.
ARG VUE_PORT
ARG VUE_SRC_DIR

# Set up working directory.
WORKDIR /app

# Copy package.json file to working directory.
COPY ./src${VUE_SRC_DIR}/package.json .

# Install packages.
RUN npm i

# Copy directory.
COPY ./src${VUE_SRC_DIR} .

# Document exposed port.
EXPOSE ${VUE_PORT}

# Start app.
ENTRYPOINT [ "npm", "run", "dev" ]
